name: MyPy Typing Check

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

defaults:
  run:
    shell: bash # opts into error checking

jobs:
  mypy:
    name: MyPy Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install MyPy and Dependencies
        run: |
          pip install mypy
          pip install -r requirements/ci.txt

      - name: Run MyPy
        run: mypy forum
